apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-claim-static
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 7200Gi
  volumeName: fsx-pv
