apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 7200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-08bfc7658e7466959
    volumeAttributes:
      dnsname: fs-08bfc7658e7466959.fsx.us-east-1.amazonaws.com
      mountname: c46oxbmv
