apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: fsx-sc
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-07dea6fc3ca6d124a
    volumeAttributes:
      dnsname: fs-07dea6fc3ca6d124a.fsx.us-east-1.amazonaws.com
      mountname: 3qpjpbmv

