apiVersion: elastic.pytorch.org/v1alpha1
kind: ElasticJob
metadata:
  name: "r50-elastic-7-autoscaler-job"
  namespace: elastic-job
spec:
  # Use "etcd-service:2379" if you already apply etcd.yaml
  # Update for scaling via template - autoscaler cfg needs to move dynamic parts out
  rdzvEndpoint: "{{etcd_server}}:2379"
  minReplicas: 1
  maxReplicas: 16
  replicaSpecs:
    Worker:
      replicas: {{num_replicas}}
      restartPolicy: ExitCode
      template:
        apiVersion: v1
        kind: Pod
        spec:
          containers:
            - name: elasticjob-worker
              image: "427566855058.dkr.ecr.us-east-1.amazonaws.com/mzanur-gradstats:resnet_elastic"
              imagePullPolicy: Always
              env:
              - name: NCCL_DEBUG
                value: "INFO"
              - name: RDMAV_FORK_SAFE
                value: "1"
              - name: NCCL_TREE_THRESHOLD
                value: "0"
              - name: NCCL_SOCKET_IFNAME
                value: "eth0"
              - name: OMP_NUM_THREADS
                value: "48"
              args:
                - "--nproc_per_node=4"
                - "/gradstats/resnet50/imagenet/trainer_ddp_amp_elastic.py"
                - "--arch=resnet50"
                - "/shared/benchmarking_datasets/imagenet/processed"
                - "--batch-size=64"
                - "--workers=12"
                - "--amp"
                - "--run-gns-experiment"
                - "--optimizer=AdamW"
                - "--lr=0.001"
                - "--weight-decay=0.1"
                - "--enable-autoscaler"
                - "--epochs=90"
                - "--channels-last"
                - "--label=r50_elastic_7_delme"
              resources:
                limits:
                  nvidia.com/gpu: 4
              volumeMounts:
              - name: persistent-volume
                mountPath: "/shared"
              - name: dshm
                mountPath: "/dev/shm"
          volumes:
          - name: persistent-volume
            persistentVolumeClaim:
              claimName: fsx-elastic-claim
          - name: dshm
            emptyDir:
              medium: Memory

