apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: "dev-job"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
          - name: "pytorch"
            image: "427566855058.dkr.ecr.us-east-1.amazonaws.com/mzanur-gradstats:resnet" 
            imagePullPolicy: Always
            command:
              - "/bin/sh"
              - "-c"
            args:
            - "sleep 1000000 && cd /gradstats"
            resources:
              limits:
                nvidia.com/gpu: 4
                # hugepages-2Mi: 5120Mi
                # memory: 160000Mi
                # vpc.amazonaws.com/efa: 1
            volumeMounts:
            - name: persistent-volume
              mountPath: "/shared"
            - name: dshm
              mountPath: "/dev/shm"
          volumes:
          - name: persistent-volume
            persistentVolumeClaim:
              claimName: fsx-claim
          - name: dshm
            emptyDir:
              medium: Memory

