apiVersion: eksctl.io/v1alpha5
availabilityZones:
- us-west-2b
- us-west-2a
iam:
  vpcResourceControllerPolicy: true
  withOIDC: true
kind: ClusterConfig
metadata:
  name: mzanur-eks-elastic-usw2b
  region: us-west-2
  version: "1.21"
managedNodeGroups:
- amiFamily: AmazonLinux2
  availabilityZones:
  - us-west-2b
  minSize: 1
  desiredCapacity: 2
  maxSize: 64
  disableIMDSv1: false
  disablePodIMDS: false
  iam:
    withAddonPolicies:
      albIngress: false
      appMesh: false
      appMeshPreview: false
      autoScaler: false
      certManager: false
      cloudWatch: false
      ebs: false
      efs: false
      externalDNS: false
      fsx: true
      imageBuilder: false
      xRay: false
  instanceSelector: {}
  instanceType: p3.16xlarge
  labels:
    alpha.eksctl.io/cluster-name: mzanur-eks-elastic-usw2b
    alpha.eksctl.io/nodegroup-name: worker-elastic-ng
    role: workers
  name: worker-elastic-ng
  privateNetworking: true
  efaEnabled: false
  ssh:
    allow: true
    publicKeyPath: mzanur-usw2
    enableSsm: true
  volumeIOPS: 12000
  volumeSize: 300
  volumeThroughput: 125
  volumeType: gp3
privateCluster:
  enabled: false
vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Single

