apiVersion: eksctl.io/v1alpha5
availabilityZones:
- us-east-1a
- us-east-1c
iam:
  vpcResourceControllerPolicy: true
  withOIDC: true
kind: ClusterConfig
metadata:
  name: mzanur-eks-efa-cluster
  region: us-east-1
  version: "1.19"
nodeGroups:
- amiFamily: AmazonLinux2
  availabilityZones:
  - us-east-1a
  minSize: 0
  desiredCapacity: 2
  maxSize: 32
  disableIMDSv1: false
  disablePodIMDS: false
  iam:
    withAddonPolicies:
      albIngress: false
      appMesh: null
      appMeshPreview: null
      autoScaler: false
      certManager: false
      cloudWatch: false
      ebs: false
      efs: false
      externalDNS: false
      fsx: true
      imageBuilder: false
      xRay: false
  instanceSelector: {}
  instanceType: p3dn.24xlarge
  labels:
    alpha.eksctl.io/cluster-name: mzanur-eks-cluster
    alpha.eksctl.io/nodegroup-name: mzanur-worker-ng
    role: workers
  name: mzanur-worker-ng
  privateNetworking: true
  efaEnabled: true
  ssh:
    allow: true
    publicKeyPath: mzanur-eks
  volumeIOPS: 3000
  volumeSize: 300
  volumeThroughput: 125
  volumeType: gp3
privateCluster:
  enabled: false
vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Single
