apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: "mrcnn-8x-job"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: "pytorch"
            image: "427566855058.dkr.ecr.us-east-1.amazonaws.com/mzanur-gradstats:mrcnn"
            imagePullPolicy: Always
            command:
              - "/bin/sh"
              - "-c"
            args:
            - "cd /gradstats/maskrcnn && ./launch_adascale_sgdw_nx.sh 8.0 /shared/export/logs/mrcnn/8x/"
            resources:
              limits:
                nvidia.com/gpu: 8
                hugepages-2Mi: 5120Mi
                memory: 384000Mi
                vpc.amazonaws.com/efa: 1
            volumeMounts:
            - name: persistent-volume
              mountPath: "/shared"
            - name: dshm
              mountPath: "/dev/shm"
          volumes:
          - name: persistent-volume
            persistentVolumeClaim:
              claimName: fsx-claim
          - name: dshm
            emptyDir:
              medium: Memory
    Worker:
      replicas: 7
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: "pytorch"
            image: "427566855058.dkr.ecr.us-east-1.amazonaws.com/mzanur-gradstats:mrcnn" 
            imagePullPolicy: Always
            command:
              - "/bin/sh"
              - "-c"
            args:
            - "cd /gradstats/maskrcnn && ./launch_adascale_sgdw_nx.sh 8.0 /shared/export/logs/mrcnn/8x/"
            resources:
              limits:
                nvidia.com/gpu: 8
                hugepages-2Mi: 5120Mi
                memory: 384000Mi
                vpc.amazonaws.com/efa: 1
            volumeMounts:
            - name: persistent-volume
              mountPath: "/shared"
            - name: dshm
              mountPath: "/dev/shm"
          volumes:
          - name: persistent-volume
            persistentVolumeClaim:
              claimName: fsx-claim
          - name: dshm
            emptyDir:
              medium: Memory
