apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: "adascale-gpu-ddp-job"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
          - name: "pytorch"
            image: "427566855058.dkr.ecr.us-east-1.amazonaws.com/mzanur-gradstats:latest" 
            command:
              - "/bin/sh"
              - "-c"
            args:
            - "sleep 100 && nvidia-smi"
            resources:
              limits:
                nvidia.com/gpu: 1
            volumeMounts:
            - name: persistent-volume
              mountPath: "/shared"
          volumes:
          - name: persistent-volume
            persistentVolumeClaim:
              claimName: fsx-claim
    Worker:
      replicas: 7
      restartPolicy: Never
      template:
        spec:
          containers:
          - name: "pytorch"
            image: "427566855058.dkr.ecr.us-east-1.amazonaws.com/mzanur-gradstats:latest" 
            command:
              - "/bin/sh"
              - "-c"
            args:
            - "nvidia-smi"
            resources:
              limits:
                nvidia.com/gpu: 1
            volumeMounts:
            - name: persistent-volume
              mountPath: "/shared"
          volumes:
          - name: persistent-volume
            persistentVolumeClaim:
              claimName: fsx-claim

