kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fsx-sc
provisioner: fsx.csi.aws.com
parameters:
  # subnet where your workers are
  subnetId: "subnet-0638aba59c557ce24"
  # sg id of worker
  securityGroupIds: "sg-0925c7d15b1aee0f0"
  # S3 datasets path
  s3ImportPath: s3://mzanur-autoscaler/
  # S3 output path
  s3ExportPath: s3://mzanur-autoscaler/export
  deploymentType: SCRATCH_2
  # autoImportPolicy: NEW_CHANGED
mountOptions:
  - flock
