kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fsx-sc
provisioner: fsx.csi.aws.com
parameters:
  # subnet where your workers are
  subnetId: "subnet-0ec2fdcb8bae402f8"
  # sg id of worker - must allow port 988 for Lustre 
  securityGroupIds: "sg-003677543e2c49056"
  # S3 datasets path
  s3ImportPath: s3://mzanur-autoscaler/
  # S3 output path
  s3ExportPath: s3://mzanur-autoscaler/export
  deploymentType: SCRATCH_2
  # autoImportPolicy: NEW_CHANGED
mountOptions:
  - flock
